# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on :
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        ts-project: [tsconfig.json]

    env:
      TS_NODE_PROJECT: ${{ matrix.ts-project }}

    steps:
    - uses: actions/checkout@v2
      name: Use Node.js ${{ matrix.node-version }}

    - uses: actions/setup-node@v2
      name: 'npm install && npm build && npm publish'
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: 'npm'
    - run: npm cache clean --force
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
    - run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
